.PHONY: clean All

All:
	@echo "----------Building project:[ SlidingWindow - Debug ]----------"
	@cd "SlidingWindow" && "$(MAKE)" -f  "SlidingWindow.mk"
clean:
	@echo "----------Cleaning project:[ SlidingWindow - Debug ]----------"
	@cd "SlidingWindow" && "$(MAKE)" -f  "SlidingWindow.mk" clean
